CREATE DATABASE DSS;
USE DSS;

-- CREATE STATEMENT
CREATE TABLE ACTORS(
	ACTOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    GENDER CHAR(1),
    AGE INT
);
-- INSERT STATEMENT
INSERT INTO ACTORS VALUES(1, 'Brad','Pitt','M',44);
INSERT INTO ACTORS VALUES(2, 'Tom','Cruise','M',50);
INSERT INTO ACTORS VALUES(3, 'Chris','Helmsworth','M',22);
INSERT INTO ACTORS VALUES(4, 'Jessica','Biel','F',33);
INSERT INTO ACTORS VALUES(5, 'Angela','Baby','F',18);
INSERT INTO ACTORS VALUES(6, 'Angelina','Jolene','F',45);
INSERT INTO ACTORS VALUES(7, 'Chris','Pratt','F',45);
-- UPDATE STATEMENT
-- DELETE STATEMENT
