CREATE DATABASE DSSDB;
USE DSSDB;

-- MOVIES MODULE ---
CREATE TABLE MOVIE(
 MOVIE_ID INT PRIMARY KEY,
 MOVIE_TITLE VARCHAR(50),
 MOVIE_RATE INT,
 MOVE_YEAR INT
 );
 
INSERT INTO MOVIE VALUES(1,"Lord of the rings",19,2006);
INSERT INTO MOVIE VALUES(2,"Fast and Furious 8",14,2018);
INSERT INTO MOVIE VALUES(3,"Nobody",18,2021);
INSERT INTO MOVIE VALUES(4,"Hunger Games",12,2010);


