CREATE DATABASE DSS;
USE DSS;

-- CREATE STATEMENTS
CREATE TABLE RATINGS (
    RATING_ID INT PRIMARY KEY,
    RATING_SCORE INT
);

-- INSERT STATEMENTS
INSERT INTO RATINGS VALUES(1, 5);
INSERT INTO RATINGS VALUES(2, 3);
INSERT INTO RATINGS VALUES(3, 2);

-- UPDATE STATEMENTS

-- DELETE STATEMENTS
