CREATE DATABASE DSS;
USE DSS;

-- CREATE STATEMENTS
CREATE TABLE REVIEWS (
    REVIEW_ID INT PRIMARY KEY,
    DATE_POSTED DATETIME,
    DESCRIPTION VARCHAR(50),
    RATING INT
);

-- INSERT STATEMENTS
INSERT INTO REVIEWS VALUES(1, "1970-01-01 00:00:01", "This was a great film! 5-star awesomeness", 5);
INSERT INTO REVIEWS VALUES(2, "2020-05-01 13:00:30", "Pretty average overrall, nothing much...", 3);

-- UPDATE STATEMENTS

-- DELETE STATEMENTS
